style: spinner
hooks:
  - id: golangci-lint
    run: golangci-lint run

  - id: goreleaser snapshot
    run: goreleaser --snapshot --rm-dist

  - id: go test
    run: go test ./...

  - id: schema
    run: |
      go run . schema > schema.json
      git diff --quiet schema.json
