// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockstest

import common "github.com/eberkund/foreplay/output/common"
import config "github.com/eberkund/foreplay/config"
import context "context"
import mock "github.com/stretchr/testify/mock"

// Registerable is an autogenerated mock type for the Registerable type
type Registerable struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, hooks, results
func (_m *Registerable) Run(ctx context.Context, hooks []config.Hook, results <-chan common.Result) {
	_m.Called(ctx, hooks, results)
}
