// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package run

// Injectors from wire.go:

func InitializeRunner() (*Run, error) {
	string2, err := GetShell()
	if err != nil {
		return nil, err
	}
	config, err := GetConfig()
	if err != nil {
		return nil, err
	}
	registerable := GetPrinter(config)
	run := GetRun(string2, config, registerable)
	return run, nil
}
