name: foreplay
adopt-info: foreplay
summary: A pre-commit hook manager
description: |
  A pre-commit hook manager
grade: stable
confinement: strict
base: core20

apps:
  foreplay:
    command: bin/foreplay
    plugs: [home]

parts:
  foreplay:
    plugin: go
    source: .
    build-packages:
      - git
      - build-essential
    build-environment:
      - GOBIN: $SNAPCRAFT_PART_INSTALL/bin
    override-build: |
      export VERSION=$(git describe --tags --abbrev=0)
      go install -ldflags="-X foreplay/cmd.version=$VERSION"
      snapcraftctl set-version $(foreplay version)
