name: CI

on: [push]

env:
  GOFLAGS: -mod=readonly -ldflags=-w

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Go Build
        run: go build

      - name: Go Test
        run: go test ./... -coverpkg=./... -covermode=count -coverprofile=coverage.txt

      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
